### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by ajh123** [tkbstudios/ccbank-client#1]
Adding a license will control what people can legally do with your code. Currently we are not legally allowed to install your software, even though the code is public on GitHub it doesn't mean we can use it. (see more: https://choosealicense.com/no-permission/) Currently you are legally liable for any issues that occur, this may become an issue in the future if no license is applied.

To add a license create a file called `LICENSE` inside the root of this repository and paste the content of the license of your choice inside it (and modify placeholders if there are any). To choose a license visit https://choosealicense.com. (just saying it in the README is not enough because GitHub will mark this repository has not having a license)

Personally, I recommend the MIT (found at https://choosealicense.com/licenses/mit/). Also I recommend do this on your other repositories.

**Comment by tkbstudios** [comment]
Thanks! will add one rn!

**Comment by tkbstudios** [comment]
This has been done.
